### ISSUE TITLE
Example from README doesn't work

### ISSUE THREAD

**Issue by pavelzw** [conda-incubator/conda-mirror#75]
```
❯ pixi exec conda-mirror --upstream-channel=robostack --target-directory=local_mirror --platform=linux-64
Traceback (most recent call last):
  File "/Users/pavel/Library/Caches/rattler/cache/cached-envs-v0/conda-mirror-b482ec466123b7da/bin/conda-mirror", line 10, in <module>
    sys.exit(cli())
             ~~~^^
  File "/Users/pavel/Library/Caches/rattler/cache/cached-envs-v0/conda-mirror-b482ec466123b7da/lib/python3.13/site-packages/conda_mirror/conda_mirror.py", line 527, in cli
    main(**_parse_and_format_args())
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/pavel/Library/Caches/rattler/cache/cached-envs-v0/conda-mirror-b482ec466123b7da/lib/python3.13/site-packages/conda_mirror/conda_mirror.py", line 438, in _parse_and_format_args
    given_args, _ = parser._parse_known_args(sys.argv[1:], argparse.Namespace())
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParser._parse_known_args() missing 1 required positional argument: 'intermixed'
```

**Comment by k-dominik** [comment]
I ran into the same issue @pavelzw and it's because of usage of a private function (`ArgumentParser._parse_known_args`) from the Python standard library, which has recently changed.

I found that it still works with Python `3.11`.
